### ISSUE TITLE
Naming convention violation within Hackney.Core.Enums TargetType.

### ISSUE THREAD

**Issue by Duslerke** [LBHackney-IT/Hackney.Core#54]
# Issue:
C# enum values should be PascalCased _(refer to: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)_.

https://github.com/LBHackney-IT/lbh-core/blob/0e1ac60e865c022297af22b54bd23cfd732d9ea7/Hackney.Core/Hackney.Core.Enums/TargetType.cs#L8-L12

# Why fix it:
I was considering using this enum until I saw that the value names are not in proper casing. I think this should be fixed before any more applications start using this enum to avoid the incorrect naming convention from spreading into other codebases.

# Notes:
This fix should increment the major version of this package as changing the naming case of this enum is a non-backwards-compatible change.

**Comment by martapederiva** [comment]
Addressed in [6a5cbc5](https://github.com/LBHackney-IT/lbh-core/commit/6a5cbc5c5754a3dbb4ebb65c5a2d0918495a5c38).
